import type { Question, Section } from "@/lib/data";

export const METRICS_QUESTIONS: Question[] = [
  {
    id: 1,
    topic: "overview",
    q: "Neste tema, qual é a classe positiva no exemplo da elipse?",
    opts: [
      "Pontos dentro da elipse.",
      "Pontos fora da elipse.",
      "Pontos sobre os eixos do gráfico.",
      "Pontos classificados como retas.",
    ],
    correct: 0,
    exp: "A rede quer reconhecer a elipse. Portanto, 'positivo' significa pertencer à elipse real.",
  },
  {
    id: 2,
    topic: "overview",
    q: "O classificador da questão descrita aproximava a elipse usando:",
    opts: [
      "Um círculo perfeito.",
      "Um retângulo definido por retas.",
      "Uma função softmax sobre todas as regiões.",
      "Uma rede recorrente.",
    ],
    correct: 1,
    exp: "A armadilha é comparar a região real curva com a região prevista retangular.",
  },
  {
    id: 3,
    topic: "counts",
    q: "PV/TP representa:",
    opts: [
      "Pontos fora da elipse e classificados como fora.",
      "Pontos dentro da elipse e classificados como dentro.",
      "Pontos fora da elipse, mas classificados como dentro.",
      "Pontos dentro da elipse, mas classificados como fora.",
    ],
    correct: 1,
    exp: "Verdadeiro positivo: o ponto é positivo de verdade e o modelo também previu positivo.",
  },
  {
    id: 4,
    topic: "counts",
    q: "PF/FP representa:",
    opts: [
      "Pontos fora da elipse, mas classificados como dentro.",
      "Pontos dentro da elipse e classificados como dentro.",
      "Pontos fora da elipse e classificados como fora.",
      "Pontos dentro da elipse, mas classificados como fora.",
    ],
    correct: 0,
    exp: "Falso positivo: o modelo aceitou como dentro, mas na realidade o ponto está fora da elipse.",
  },
  {
    id: 5,
    topic: "counts",
    q: "NV/TN representa:",
    opts: [
      "Pontos dentro da elipse e classificados como dentro.",
      "Pontos fora da elipse e classificados como fora.",
      "Pontos dentro da elipse, mas classificados como fora.",
      "Pontos fora da elipse, mas classificados como dentro.",
    ],
    correct: 1,
    exp: "Verdadeiro negativo: negativo real e negativo previsto.",
  },
  {
    id: 6,
    topic: "counts",
    q: "NF/FN representa:",
    opts: [
      "Pontos dentro da elipse, mas classificados como fora.",
      "Pontos fora da elipse e classificados como fora.",
      "Pontos fora da elipse, mas classificados como dentro.",
      "Pontos dentro da elipse e classificados como dentro.",
    ],
    correct: 0,
    exp: "Falso negativo: o ponto deveria ser aceite, mas o classificador rejeitou.",
  },
  {
    id: 7,
    topic: "formulas",
    q: "A fórmula correta da accuracy é:",
    opts: [
      "PV / (PV + PF)",
      "PV / (PV + NF)",
      "(PV + NV) / total",
      "PF / total",
    ],
    correct: 2,
    exp: "Accuracy mede a fração total de acertos: verdadeiros positivos + verdadeiros negativos.",
  },
  {
    id: 8,
    topic: "formulas",
    q: "A fórmula correta da precision é:",
    opts: [
      "PV / (PV + PF)",
      "PV / (PV + NF)",
      "(PV + NV) / total",
      "NV / (NV + NF)",
    ],
    correct: 0,
    exp: "Precision responde: entre os pontos que classifiquei como dentro, quantos estavam realmente dentro?",
  },
  {
    id: 9,
    topic: "formulas",
    q: "A fórmula correta do recall é:",
    opts: [
      "PV / (PV + PF)",
      "PV / (PV + NF)",
      "NV / total",
      "PF / (PF + NV)",
    ],
    correct: 1,
    exp: "Recall responde: entre os pontos que eram realmente da elipse, quantos foram recuperados?",
  },
  {
    id: 10,
    topic: "formulas",
    q: "Se PV=30, PF=10, NV=50 e NF=10, a precision é:",
    opts: ["30/40 = 0.75", "30/40 = 0.50", "80/100 = 0.80", "30/40 = 1.00"],
    correct: 0,
    exp: "Precision = PV/(PV+PF) = 30/(30+10) = 0.75.",
  },
  {
    id: 11,
    topic: "formulas",
    q: "Se PV=30, PF=10, NV=50 e NF=10, o recall é:",
    opts: ["30/40 = 0.75", "30/100 = 0.30", "50/60 = 0.83", "80/100 = 0.80"],
    correct: 0,
    exp: "Recall = PV/(PV+NF) = 30/(30+10) = 0.75.",
  },
  {
    id: 12,
    topic: "formulas",
    q: "Se PV=30, PF=10, NV=50 e NF=10, a accuracy é:",
    opts: ["30/40 = 0.75", "80/100 = 0.80", "50/60 = 0.83", "40/100 = 0.40"],
    correct: 1,
    exp: "Accuracy = (PV+NV)/total = (30+50)/100 = 0.80.",
  },
  {
    id: 13,
    topic: "ellipse_rectangle",
    q: "Se o retângulo previsto é grande demais em relação à elipse, tende a aumentar:",
    opts: ["PF/FP", "NF/FN", "NV/TN apenas", "O total de pontos reais"],
    correct: 0,
    exp: "Um retângulo grande aceita pontos fora da elipse. Isso cria falsos positivos.",
  },
  {
    id: 14,
    topic: "ellipse_rectangle",
    q: "Se o retângulo previsto é pequeno demais dentro da elipse, tende a aumentar:",
    opts: ["PF/FP", "NF/FN", "PV/TP sempre", "NV/TN nunca"],
    correct: 1,
    exp: "Um retângulo pequeno rejeita partes da elipse real. Isso cria falsos negativos.",
  },
  {
    id: 15,
    topic: "ellipse_rectangle",
    q: "Na visualização elipse real versus retângulo previsto, os pontos dentro da elipse mas fora do retângulo são:",
    opts: ["PV/TP", "PF/FP", "NV/TN", "NF/FN"],
    correct: 3,
    exp: "Eles eram positivos reais, mas o modelo classificou como fora.",
  },
  {
    id: 16,
    topic: "tradeoff",
    q: "Aumentar muito a região prevista normalmente melhora recall, mas pode piorar:",
    opts: ["precision", "total", "número de positivos reais", "definição da elipse"],
    correct: 0,
    exp: "Aceitar mais pontos recupera mais positivos, mas também pode trazer falsos positivos.",
  },
  {
    id: 17,
    topic: "tradeoff",
    q: "Diminuir muito a região prevista normalmente melhora precision, mas pode piorar:",
    opts: ["recall", "total", "a quantidade de negativos reais", "a fórmula da accuracy"],
    correct: 0,
    exp: "Uma região conservadora erra menos por falso positivo, mas pode deixar positivos reais de fora.",
  },
  {
    id: 18,
    topic: "exam2024",
    q: "No tipo de questão com regiões ra, rb, rc, rd, re, rf, o procedimento seguro é:",
    opts: [
      "Somar regiões por nome sem olhar o que significam.",
      "Classificar cada região como PV, PF, NV ou NF antes de aplicar fórmulas.",
      "Usar sempre apenas accuracy.",
      "Ignorar a região prevista.",
    ],
    correct: 1,
    exp: "As letras são só nomes. Primeiro decida verdade real e previsão para cada região.",
  },
  {
    id: 19,
    topic: "exam2024",
    q: "Se uma região está fora da elipse real e dentro do retângulo previsto, ela entra em:",
    opts: ["PV/TP", "PF/FP", "NV/TN", "NF/FN"],
    correct: 1,
    exp: "Real negativo, previsão positiva: falso positivo.",
  },
  {
    id: 20,
    topic: "review",
    q: "A pergunta que define precision é:",
    opts: [
      "De tudo que existia no total, quanto acertei?",
      "De tudo que eu chamei de positivo, quanto era positivo mesmo?",
      "De tudo que era positivo de verdade, quanto recuperei?",
      "Quantas regiões têm nome começando por r?",
    ],
    correct: 1,
    exp: "Precision mede a confiabilidade das previsões positivas.",
  },
];

export const METRICS_TOPIC_LABELS: Record<string, string> = {
  overview: "Visão geral",
  counts: "PV/PF/NV/NF",
  formulas: "Fórmulas",
  ellipse_rectangle: "Elipse vs retângulo",
  tradeoff: "Trade-off",
  exam2024: "Prova 2024",
  review: "Revisão",
};

export const METRICS_SECTIONS: Section[] = [
  {
    id: "inicio",
    num: "00",
    title: "Visão Geral",
    subtitle: "elipse real, retângulo previsto",
  },
  {
    id: "counts",
    num: "01",
    title: "PV, PF, NV, NF",
    subtitle: "a matriz de confusão no desenho",
  },
  {
    id: "formulas",
    num: "02",
    title: "Accuracy, Precision, Recall",
    subtitle: "as três fórmulas que caem",
  },
  {
    id: "ellipse_rectangle",
    num: "03",
    title: "Elipse vs Retângulo",
    subtitle: "quando retas aproximam a região curva",
  },
  {
    id: "tradeoff",
    num: "04",
    title: "Trade-off",
    subtitle: "retângulo grande, pequeno ou deslocado",
  },
  {
    id: "exam2024",
    num: "05",
    title: "Regiões ra-rf",
    subtitle: "como ler a questão de 2024",
  },
  {
    id: "review",
    num: "06",
    title: "Treino Rápido",
    subtitle: "classificar regiões antes de calcular",
  },
  {
    id: "simulado",
    num: "∞",
    title: "Simulado Final",
    subtitle: "20 questões estilo prova",
  },
];
