import type { Question, Section } from "@/lib/data";

export const PERCEPTRON_QUESTIONS: Question[] = [
  {
    id: 1,
    topic: "method",
    q: "Qual é o primeiro passo ao resolver uma figura com perceptrons geométricos?",
    opts: [
      "Escolher aleatoriamente pesos positivos.",
      "Identificar cada reta, plano ou fronteira relevante da figura.",
      "Construir diretamente uma camada OR.",
      "Aplicar softmax aos pontos do gráfico.",
    ],
    correct: 1,
    exp: "Antes de pensar em pesos, isole as fronteiras. Cada reta/plano vira uma condição do tipo w·x + b = 0.",
  },
  {
    id: 2,
    topic: "method",
    q: "Depois de escrever w1*x1 + w2*x2 + b = 0, o que decide se a saída 1 está do lado certo?",
    opts: [
      "O sinal de w1 apenas.",
      "Testar um ponto do lado desejado e verificar se w·x + b fica positivo.",
      "A quantidade de retas no desenho.",
      "O valor absoluto do bias.",
    ],
    correct: 1,
    exp: "Use um ponto-teste. Se o lado desejado der negativo, multiplique pesos e bias por -1.",
  },
  {
    id: 3,
    topic: "line_plane",
    q: "A reta x2 = 2*x1 - 3 pode ser escrita na forma de perceptron como:",
    opts: [
      "2*x1 - x2 - 3 = 0",
      "2*x1 + x2 - 3 = 0",
      "x1 + 2*x2 - 3 = 0",
      "-2*x1 - x2 + 3 = 0",
    ],
    correct: 0,
    exp: "Passe tudo para um lado: x2 = 2x1 - 3 vira 2x1 - x2 - 3 = 0.",
  },
  {
    id: 4,
    topic: "line_plane",
    q: "Para inverter o lado classificado como 1 por um perceptron, deve-se:",
    opts: [
      "Trocar apenas w1 por -w1.",
      "Trocar apenas o bias por -b.",
      "Multiplicar todos os pesos e o bias por -1.",
      "Adicionar uma camada softmax.",
    ],
    correct: 2,
    exp: "A fronteira permanece a mesma, mas o semiplano positivo troca de lado: w·x + b >= 0 vira -(w·x + b) >= 0.",
  },
  {
    id: 5,
    topic: "line_plane",
    q: "No plano 3D, a equação w1*x1 + w2*x2 + w3*x3 + b = 0 representa:",
    opts: [
      "Uma reta.",
      "Um plano.",
      "Uma elipse.",
      "Uma função softmax.",
    ],
    correct: 1,
    exp: "Em 2D a fronteira linear é uma reta. Em 3D, a fronteira linear é um plano.",
  },
  {
    id: 6,
    topic: "logic",
    q: "Se uma região deve satisfazer simultaneamente três condições lineares, a combinação correta é:",
    opts: ["OR", "NOT", "AND", "Argmax"],
    correct: 2,
    exp: "Interseção de condições = conjunção. Todos os perceptrons precisam dar 1.",
  },
  {
    id: 7,
    topic: "logic",
    q: "Um NOT geométrico para uma condição linear pode ser implementado por:",
    opts: [
      "Usar os mesmos pesos e remover o bias.",
      "Multiplicar pesos e bias por -1.",
      "Adicionar mais pontos de treino.",
      "Trocar AND por OR em todos os casos.",
    ],
    correct: 1,
    exp: "Negar uma meia-região é escolher o outro lado da mesma fronteira.",
  },
  {
    id: 8,
    topic: "logic",
    q: "Uma camada final OR é útil quando a região desejada é:",
    opts: [
      "A interseção de todas as restrições.",
      "Uma união de sub-regiões separadas ou alternativas.",
      "Sempre um único semiplano.",
      "Sempre uma reta sem área.",
    ],
    correct: 1,
    exp: "Cada sub-região pode ser construída por AND; a união entre elas exige OR na camada final.",
  },
  {
    id: 9,
    topic: "regions",
    q: "Um triângulo no plano pode ser representado, aproximadamente ou exatamente, por:",
    opts: [
      "Um único perceptron.",
      "Três semiplanos combinados por AND.",
      "Três semiplanos combinados por OR.",
      "Um softmax sobre os vértices.",
    ],
    correct: 1,
    exp: "Cada lado do triângulo define uma reta. O interior é a interseção dos três lados corretos.",
  },
  {
    id: 10,
    topic: "regions",
    q: "Uma faixa entre duas retas paralelas exige:",
    opts: [
      "Duas condições, uma para cada limite, combinadas por AND.",
      "Uma única condição OR.",
      "Nenhuma condição linear.",
      "Apenas um peso negativo sem bias.",
    ],
    correct: 0,
    exp: "A faixa é o conjunto de pontos acima de uma reta e abaixo da outra. Isso é interseção.",
  },
  {
    id: 11,
    topic: "regions",
    q: "Para aproximar uma elipse com perceptrons lineares, a estratégia usual é:",
    opts: [
      "Usar várias retas tangentes e fazer AND dos lados internos.",
      "Usar uma única reta vertical.",
      "Usar OR entre todas as retas tangentes.",
      "Remover o bias dos perceptrons.",
    ],
    correct: 0,
    exp: "Retas tangentes formam um polígono. Quanto mais retas, melhor a aproximação da elipse.",
  },
  {
    id: 12,
    topic: "regions",
    q: "A região acima de uma reta r1 e abaixo de uma reta r2 é:",
    opts: [
      "Uma união de dois semiplanos.",
      "A interseção de dois semiplanos.",
      "Sempre impossível.",
      "Sempre uma elipse.",
    ],
    correct: 1,
    exp: "O ponto precisa passar simultaneamente nos dois testes: acima de r1 AND abaixo de r2.",
  },
  {
    id: 13,
    topic: "ellipses",
    q: "Por que um único AND global pode falhar para duas elipses sobrepostas?",
    opts: [
      "Porque AND global calcula a união das elipses.",
      "Porque AND global intersecta todas as restrições, podendo deixar só a zona comum.",
      "Porque elipses não podem ser aproximadas por retas.",
      "Porque OR só funciona em 3D.",
    ],
    correct: 1,
    exp: "Se você junta todas as retas das duas elipses num AND só, está pedindo pontos dentro das duas ao mesmo tempo.",
  },
  {
    id: 14,
    topic: "ellipses",
    q: "A arquitetura correta para a união de duas elipses aproximadas por retas é:",
    opts: [
      "AND de todas as retas das duas elipses.",
      "Elipse A por AND, elipse B por AND, depois OR entre A e B.",
      "OR entre todas as retas individuais.",
      "NOT da primeira elipse apenas.",
    ],
    correct: 1,
    exp: "Construa cada sub-região de forma independente. Depois una as sub-regiões com uma camada OR.",
  },
  {
    id: 15,
    topic: "ellipses",
    q: "Na prova de maio de 2025, a armadilha das duas elipses destacava principalmente:",
    opts: [
      "A diferença entre interseção global e união de sub-regiões.",
      "A necessidade de usar recorrência.",
      "A impossibilidade de usar bias.",
      "A soma das probabilidades do softmax.",
    ],
    correct: 0,
    exp: "A ideia-chave é não confundir juntar todas as restrições com construir cada região e aplicar OR depois.",
  },
  {
    id: 16,
    topic: "planes",
    q: "A região entre dois planos paralelos em 3D é análoga, em 2D, a:",
    opts: [
      "Um triângulo.",
      "Uma faixa entre duas retas paralelas.",
      "Uma única reta.",
      "Uma união de elipses.",
    ],
    correct: 1,
    exp: "Em ambos os casos há dois limites paralelos e a região desejada fica entre eles.",
  },
  {
    id: 17,
    topic: "planes",
    q: "Para ficar entre dois planos paralelos, a combinação lógica das duas condições deve ser:",
    opts: ["AND", "OR", "NOT apenas", "XOR sempre"],
    correct: 0,
    exp: "O ponto precisa estar do lado correto do primeiro plano e do lado correto do segundo.",
  },
  {
    id: 18,
    topic: "planes",
    q: "Se o plano é w·x + b = 0, o vetor w indica:",
    opts: [
      "A normal do plano, isto é, a direção perpendicular à fronteira.",
      "O centro de uma elipse.",
      "A quantidade de camadas da rede.",
      "A saída final da função degrau.",
    ],
    correct: 0,
    exp: "O vetor de pesos aponta perpendicularmente à reta/plano de decisão.",
  },
  {
    id: 19,
    topic: "method",
    q: "Um ponto-teste do lado desejado produz w·x + b < 0. O que fazer?",
    opts: [
      "Aceitar, porque qualquer lado serve.",
      "Multiplicar pesos e bias por -1.",
      "Remover a condição.",
      "Trocar AND por softmax.",
    ],
    correct: 1,
    exp: "O lado desejado deve ser o lado positivo quando a saída 1 é step(w·x + b).",
  },
  {
    id: 20,
    topic: "logic",
    q: "A regra y = step(x1 + x2 - 0.5), para entradas binárias, implementa:",
    opts: ["AND", "OR", "NOT x1", "NAND"],
    correct: 1,
    exp: "Basta uma entrada igual a 1 para a soma passar de 0.5.",
  },
  {
    id: 21,
    topic: "logic",
    q: "A regra y = step(x1 + x2 - 1.5), para entradas binárias, implementa:",
    opts: ["OR", "AND", "NOT", "NOR"],
    correct: 1,
    exp: "Só quando x1=1 e x2=1 a soma supera 1.5.",
  },
  {
    id: 22,
    topic: "regions",
    q: "Se uma figura pede 'fora da região A ou dentro da região B', isso sugere:",
    opts: [
      "NOT(A) combinado por OR com B.",
      "AND global de A e B.",
      "Remover todas as fronteiras de A.",
      "Apenas uma reta horizontal.",
    ],
    correct: 0,
    exp: "Traduza a frase lógica literalmente: fora = NOT, ou = OR.",
  },
  {
    id: 23,
    topic: "line_plane",
    q: "O bias b em w·x + b = 0 controla principalmente:",
    opts: [
      "O deslocamento da fronteira em relação à origem.",
      "A cor do gráfico.",
      "A quantidade de neurónios na camada final.",
      "A normalização dos dados para somar 1.",
    ],
    correct: 0,
    exp: "Com w fixo, mudar b desloca a reta/plano paralelamente.",
  },
  {
    id: 24,
    topic: "regions",
    q: "Aumentar o número de retas usadas para aproximar uma elipse tende a:",
    opts: [
      "Piorar a aproximação.",
      "Melhorar a aproximação, aproximando o polígono da curva.",
      "Eliminar a necessidade de AND.",
      "Transformar a elipse numa reta.",
    ],
    correct: 1,
    exp: "Mais tangentes criam um polígono com mais lados e erro menor em relação à elipse.",
  },
  {
    id: 25,
    topic: "review",
    q: "A ordem mental mais segura para resolver exercícios de perceptrons geométricos é:",
    opts: [
      "Escolher OR, depois desenhar qualquer reta.",
      "Identificar fronteiras, escrever equações, orientar o lado 1, combinar as saídas.",
      "Começar pelo simulado e só depois olhar para a figura.",
      "Usar sempre um AND global.",
    ],
    correct: 1,
    exp: "Essa é a rotina diária: fronteira → equação → lado positivo → composição lógica.",
  },
];

export const PERCEPTRON_TOPIC_LABELS: Record<string, string> = {
  method: "Método",
  line_plane: "Retas e planos",
  logic: "AND/OR/NOT",
  regions: "Regiões 2D",
  ellipses: "União de elipses",
  planes: "Planos 3D",
  review: "Revisão",
};

export const PERCEPTRON_SECTIONS: Section[] = [
  {
    id: "inicio",
    num: "00",
    title: "Visão Geral",
    subtitle: "O método que você repete todos os dias",
  },
  {
    id: "method",
    num: "01",
    title: "Método dos 4 Passos",
    subtitle: "Fronteira, equação, lado, combinação",
  },
  {
    id: "line_plane",
    num: "02",
    title: "Retas e Planos",
    subtitle: "Da figura para w·x + b = 0",
  },
  {
    id: "logic",
    num: "03",
    title: "AND, NOT e OR",
    subtitle: "Como combinar perceptrons",
  },
  {
    id: "regions",
    num: "04",
    title: "Regiões 2D",
    subtitle: "Triângulo, faixa, cunha e elipse",
  },
  {
    id: "ellipses",
    num: "05",
    title: "Duas Elipses",
    subtitle: "A armadilha do AND global",
  },
  {
    id: "planes",
    num: "06",
    title: "Planos 3D",
    subtitle: "A região entre dois planos",
  },
  {
    id: "review",
    num: "07",
    title: "Treino Diário",
    subtitle: "Exercícios rápidos antes da prova",
  },
  {
    id: "simulado",
    num: "∞",
    title: "Simulado Final",
    subtitle: "25 questões estilo prova",
  },
];
