import type { Question, Section } from "@/lib/data";

export const RANTIA_QUESTIONS: Question[] = [
  {
    id: 1,
    topic: "course_map",
    q: "Qual afirmação define melhor um sistema ciber-físico?",
    opts: [
      "Sistema puramente mecânico sem software.",
      "Software/comunicação integrados com um processo físico, com influência bidirecional.",
      "Apenas armazenamento cloud.",
      "Processo simulado sem ligação ao mundo real.",
    ],
    correct: 1,
    exp: "Sistema ciber-físico = software e processo físico influenciam-se mutuamente. A chave é a bidirecionalidade.",
  },
  {
    id: 2,
    topic: "course_map",
    q: "As camadas RAMI 4.0 são:",
    opts: [
      "Physical, Network, Transport, Application.",
      "Asset, Integration, Communication, Information, Functional, Business.",
      "Sensor, Actuator, Controller, Cloud.",
      "Input, Processing, Output, Storage.",
    ],
    correct: 1,
    exp: "RAMI 4.0: Asset, Integration, Communication, Information, Functional, Business.",
  },
  {
    id: 3,
    topic: "robotics_fundamentals",
    q: "Repeatability num robot industrial significa:",
    opts: [
      "A velocidade máxima de movimento.",
      "A capacidade de retornar repetidamente à mesma posição.",
      "O número máximo de eixos.",
      "A resolução do sensor.",
    ],
    correct: 1,
    exp: "Repeatability = capacidade de retornar à mesma posição repetidamente. Diferente de resolução e accuracy.",
  },
  {
    id: 4,
    topic: "robotics_fundamentals",
    q: "MoveL em RAPID significa:",
    opts: [
      "Movimento articular no espaço das juntas.",
      "Movimento linear no espaço operacional/task space.",
      "Paragem de emergência.",
      "Calibração automática.",
    ],
    correct: 1,
    exp: "MoveL = interpolação linear no espaço operacional. Não é espaço articular.",
  },
  {
    id: 5,
    topic: "ros2_architecture",
    q: "A principal diferença entre ROS1 e ROS2 é:",
    opts: [
      "ROS1 usa DDS.",
      "ROS2 usa DDS e não requer ROS Master/roscore.",
      "ROS2 só funciona em Ubuntu.",
      "Os pacotes ROS2 são diretamente compatíveis com ROS1.",
    ],
    correct: 1,
    exp: "ROS2 usa DDS para discovery/comunicação e não precisa de roscore/ROS Master. ROS1 usa TCPROS e requer roscore.",
  },
  {
    id: 6,
    topic: "ros2_architecture",
    q: "Qual comando lista os nós ROS2 ativos?",
    opts: [
      "ros2 topic list",
      "ros2 node list",
      "ros2 service list",
      "rosnode list",
    ],
    correct: 1,
    exp: "`ros2 node list` lista nós. `rosnode list` é ROS1. Atenção à armadilha ROS1 vs ROS2.",
  },
  {
    id: 7,
    topic: "ros2_project",
    q: "O ficheiro que especifica dependências de um pacote ROS2 é:",
    opts: [
      "CMakeLists.txt",
      "package.xml",
      "setup.py",
      "colcon.yaml",
    ],
    correct: 1,
    exp: "package.xml especifica metadados e dependências do pacote. CMakeLists.txt é para build C++.",
  },
  {
    id: 8,
    topic: "ros2_project",
    q: "RViz2 é:",
    opts: [
      "Um simulador de física 3D.",
      "Um visualizador de dados ROS2 (TF, sensores, odometria).",
      "Uma ferramenta de controlo de motores.",
      "Um compilador de pacotes.",
    ],
    correct: 1,
    exp: "RViz2 visualiza dados ROS2. NÃO é simulador — Gazebo/Webots são simuladores.",
  },
  {
    id: 9,
    topic: "simulation",
    q: "A diferença entre URDF e SDF é:",
    opts: [
      "São exatamente iguais.",
      "URDF descreve a estrutura do robot; SDF pode descrever modelos de simulação e mundos completos.",
      "SDF é apenas para Arduino.",
      "URDF inclui terreno e iluminação.",
    ],
    correct: 1,
    exp: "URDF = estrutura do robot (links, joints). SDF = modelos de simulação + mundos (terreno, luzes, sensores, plugins).",
  },
  {
    id: 10,
    topic: "simulation",
    q: "O sim-to-real gap refere-se a:",
    opts: [
      "O custo de um robot real.",
      "A diferença entre física/sensores simulados e o mundo real.",
      "A velocidade de compilação.",
      "O tamanho do ficheiro URDF.",
    ],
    correct: 1,
    exp: "Sim-to-real gap = diferenças entre simulação e realidade (física, sensores, latência, fricção, iluminação).",
  },
  {
    id: 11,
    topic: "computer_vision",
    q: "No modelo HSV, o H (Hue) representa:",
    opts: [
      "O brilho.",
      "A saturação/pureza.",
      "A cor em si.",
      "O contraste.",
    ],
    correct: 2,
    exp: "HSV: H = cor (matiz), S = saturação/pureza, V = valor/brilho.",
  },
  {
    id: 12,
    topic: "computer_vision",
    q: "O cv_bridge no ROS2 serve para:",
    opts: [
      "Simular câmaras.",
      "Converter entre mensagens ROS2 Image e arrays OpenCV/NumPy.",
      "Controlar motores.",
      "Compilar pacotes.",
    ],
    correct: 1,
    exp: "cv_bridge converte entre formatos ROS2 Image e OpenCV/NumPy para processamento de visão.",
  },
  {
    id: 13,
    topic: "distributed_robotics",
    q: "O papel de um bridge ROS2-MQTT é:",
    opts: [
      "Substituir completamente o DDS.",
      "Ligar a comunicação interna ROS2/DDS a brokers MQTT externos para IoT/cloud.",
      "Compilar código ROS2.",
      "Simular sensores.",
    ],
    correct: 1,
    exp: "Bridge = ligação entre ROS2/DDS interno e MQTT externo. NÃO substitui DDS.",
  },
  {
    id: 14,
    topic: "distributed_robotics",
    q: "Um risco de bridging indiscriminado de tópicos é:",
    opts: [
      "Melhor performance garantida.",
      "Latência, dados obsoletos, sobrecarga de bandwidth e QoS mismatch.",
      "Eliminação de todos os problemas de rede.",
      "Compilação mais rápida.",
    ],
    correct: 1,
    exp: "Bridging indiscriminado pode causar latência, dados obsoletos, race conditions, sobrecarga e QoS mismatch.",
  },
  {
    id: 15,
    topic: "iot_foundations",
    q: "AIoT combina:",
    opts: [
      "Apenas hardware mecânico.",
      "IoT (conectividade/dados) com AI (inteligência/decisão).",
      "Apenas armazenamento local.",
      "Apenas redes LAN.",
    ],
    correct: 1,
    exp: "AIoT = Artificial Intelligence of Things. Combina conectividade/dados IoT com análise/decisão AI.",
  },
  {
    id: 16,
    topic: "iot_foundations",
    q: "Edge AI processa dados:",
    opts: [
      "Apenas na cloud central.",
      "Perto do dispositivo para reduzir latência, bandwidth e riscos de privacidade.",
      "Apenas em papel.",
      "Sem qualquer processamento.",
    ],
    correct: 1,
    exp: "Edge AI = processamento local/próximo do dispositivo. Reduz latência, bandwidth e riscos de privacidade.",
  },
  {
    id: 17,
    topic: "sensors_electronics",
    q: "Com dois resistores de 1 kΩ em série a 10V, a corrente é:",
    opts: [
      "10 mA",
      "5 mA",
      "2.5 mA",
      "20 mA",
    ],
    correct: 1,
    exp: "V = I × R. R total = 2 kΩ. I = 10V / 2000Ω = 5 mA.",
  },
  {
    id: 18,
    topic: "sensors_electronics",
    q: "Arduino Uno analogRead() retorna valores no intervalo:",
    opts: [
      "0–255",
      "0–1023",
      "0–4095",
      "0–65535",
    ],
    correct: 1,
    exp: "Arduino Uno ADC = 10 bits = 0–1023. ESP32 ADC = 12 bits = 0–4095.",
  },
  {
    id: 19,
    topic: "sensors_electronics",
    q: "attachInterrupt(..., RISING) dispara quando:",
    opts: [
      "O sinal desce de HIGH para LOW.",
      "O sinal sobe de LOW para HIGH.",
      "O sinal está sempre HIGH.",
      "O botão é premido e mantido.",
    ],
    correct: 1,
    exp: "RISING = transição de LOW para HIGH. FALLING = HIGH para LOW.",
  },
  {
    id: 20,
    topic: "sensors_electronics",
    q: "Um resistor pull-up serve para:",
    opts: [
      "Aumentar a tensão de alimentação.",
      "Evitar input flutuante e manter HIGH quando o botão está aberto.",
      "Controlar a velocidade do motor.",
      "Medir temperatura.",
    ],
    correct: 1,
    exp: "Pull-up = previne floating e mantém HIGH quando o botão não está premido.",
  },
  {
    id: 21,
    topic: "iot_protocols",
    q: "MQTT QoS 2 garante:",
    opts: [
      "At most once.",
      "At least once.",
      "Exactly once.",
      "Nenhuma garantia.",
    ],
    correct: 2,
    exp: "QoS 0 = at most once. QoS 1 = at least once. QoS 2 = exactly once.",
  },
  {
    id: 22,
    topic: "iot_protocols",
    q: "O wildcard MQTT + faz match de:",
    opts: [
      "Múltiplos níveis de tópico.",
      "Exatamente um nível de tópico.",
      "Todos os tópicos do broker.",
      "Nenhum tópico.",
    ],
    correct: 1,
    exp: "+ = um nível exato. # = múltiplos níveis. devices/+/battery match devices/sensor1/battery mas NÃO devices/sensor1/battery/level.",
  },
  {
    id: 23,
    topic: "iot_protocols",
    q: "Para permitir clientes anónimos no Mosquitto, usa-se:",
    opts: [
      "anonymous_clients = yes",
      "allow_anonymous true",
      "mqtt.anonymous.enable()",
      "set_anon true",
    ],
    correct: 1,
    exp: "Diretiva Mosquitto: allow_anonymous true.",
  },
  {
    id: 24,
    topic: "iot_clouds",
    q: "A jornada típica de dados IoT é:",
    opts: [
      "Cloud → Device → User.",
      "Device/Sensor → Gateway/Edge → Cloud Ingestion → Processing → Storage/Analytics → Dashboard.",
      "Dashboard → Sensor → Cloud.",
      "User → Cloud → Sensor.",
    ],
    correct: 1,
    exp: "Device → Gateway/Edge → Cloud Ingestion → Stream Processing → Storage/Analytics → Dashboard/API/Action.",
  },
  {
    id: 25,
    topic: "iot_clouds",
    q: "Um digital twin é:",
    opts: [
      "Uma cópia física do robot.",
      "Uma representação digital de um sistema físico para monitorização e análise.",
      "Um tipo de sensor.",
      "Um protocolo de comunicação.",
    ],
    correct: 1,
    exp: "Digital twin = representação digital de um sistema físico. Permite monitorização, simulação e análise.",
  },
];

export const RANTIA_TOPIC_LABELS: Record<string, string> = {
  course_map: "Mapa do Curso",
  robotics_fundamentals: "Fundamentos de Robótica",
  ros2_architecture: "ROS2 Arquitetura",
  ros2_project: "ROS2 Projeto",
  simulation: "Simulação",
  computer_vision: "Visão Computacional",
  distributed_robotics: "Robótica Distribuída",
  iot_foundations: "Fundamentos IoT",
  sensors_electronics: "Sensores e Eletrónica",
  iot_protocols: "Protocolos IoT",
  iot_clouds: "IoT Cloud",
};

export const RANTIA_SECTIONS: Section[] = [
  {
    id: "inicio",
    num: "00",
    title: "Visão Geral",
    subtitle: "Guia de estudo RAINTIA",
  },
  {
    id: "course_map",
    num: "01",
    title: "Mapa do Curso",
    subtitle: "Robótica inteligente, ambientes e Industry 4.0",
  },
  {
    id: "robotics_fundamentals",
    num: "02",
    title: "Fundamentos de Robótica",
    subtitle: "Manipuladores, DoF, cobots e especificações",
  },
  {
    id: "ros2_architecture",
    num: "03",
    title: "ROS2 Arquitetura e CLI",
    subtitle: "Nós, tópicos, DDS, QoS e comandos",
  },
  {
    id: "ros2_project",
    num: "04",
    title: "ROS2 Projeto e Ferramentas",
    subtitle: "Packages, launch, RViz2, rqt_graph e TF",
  },
  {
    id: "simulation",
    num: "05",
    title: "Simulação",
    subtitle: "Gazebo, Webots, URDF, SDF e LiDAR",
  },
  {
    id: "computer_vision",
    num: "06",
    title: "Visão Computacional",
    subtitle: "cv_bridge, OpenCV, YOLO e HSV",
  },
  {
    id: "distributed_robotics",
    num: "07",
    title: "Robótica Distribuída",
    subtitle: "DDS, MQTT, bridges e data fusion",
  },
  {
    id: "iot_foundations",
    num: "08",
    title: "Fundamentos IoT",
    subtitle: "AIoT, edge AI, TinyML e federated learning",
  },
  {
    id: "sensors_electronics",
    num: "09",
    title: "Sensores e Eletrónica",
    subtitle: "Arduino, ESP32, ADC, PWM e interrupts",
  },
  {
    id: "iot_protocols",
    num: "10",
    title: "Protocolos IoT e MQTT",
    subtitle: "QoS, wildcards, Mosquitto e wireless",
  },
  {
    id: "iot_clouds",
    num: "11",
    title: "IoT Cloud e Digital Twins",
    subtitle: "Edge/cloud, plataformas e gémeos digitais",
  },
  {
    id: "assessment",
    num: "12",
    title: "Avaliação Final",
    subtitle: "Exame simulado 45 minutos",
  },
];
