import type { Question, Section } from "@/lib/data";

export const SIMAGIA_QUESTIONS: Question[] = [
  {
    id: 1,
    topic: "agentes_ambientes",
    q: "Qual das seguintes NÃO é uma propriedade da noção fraca de agência?",
    opts: [
      "Autonomia.",
      "Capacidade social.",
      "Mobilidade.",
      "Proatividade.",
    ],
    correct: 2,
    exp: "A noção fraca inclui autonomia, capacidade social, reatividade e proatividade. Mobilidade pertence à noção forte de agência.",
  },
  {
    id: 2,
    topic: "agentes_ambientes",
    q: "Um agente difere de um objeto porque:",
    opts: [
      "Objetos não têm estado.",
      "Agentes decidem autonomamente se executam ou não uma ação.",
      "Objetos comunicam através de linguagens de alto nível.",
      "Agentes não encapsulam estado.",
    ],
    correct: 1,
    exp: "Objetos encapsulam estado e métodos, mas normalmente não decidem autonomamente. Agentes controlam o seu próprio comportamento.",
  },
  {
    id: 3,
    topic: "agentes_ambientes",
    q: "Um ambiente inacessível e dinâmico dificulta a tomada de decisão porque:",
    opts: [
      "O agente tem informação completa e o mundo não muda.",
      "O agente tem informação parcial e o mundo pode mudar fora do seu controlo.",
      "O ambiente é sempre determinístico.",
      "O agente não precisa de sensores.",
    ],
    correct: 1,
    exp: "Inacessível = informação parcial. Dinâmico = o mundo muda independentemente do agente. Ambos tornam planos obsoletos.",
  },
  {
    id: 4,
    topic: "arquiteturas",
    q: "A arquitetura reativa é mais adequada quando:",
    opts: [
      "É necessário planeamento a longo prazo.",
      "O ambiente é dinâmico e exige resposta rápida.",
      "O agente precisa de raciocinar simbolicamente.",
      "O problema requer representação completa do mundo.",
    ],
    correct: 1,
    exp: "Reativa = perceção→ação direta. Rápida e robusta em ambientes dinâmicos, mas fraca em planeamento a longo prazo.",
  },
  {
    id: 5,
    topic: "arquiteturas",
    q: "No modelo BDI, uma intenção é:",
    opts: [
      "Qualquer objetivo possível do agente.",
      "Informação que o agente tem sobre o ambiente.",
      "Um desejo selecionado e comprometido através de um plano.",
      "Uma ação executada automaticamente.",
    ],
    correct: 2,
    exp: "Desejo = objetivo possível. Intenção = desejo selecionado com compromisso de execução via plano.",
  },
  {
    id: 6,
    topic: "arquiteturas",
    q: "Uma arquitetura híbrida combina:",
    opts: [
      "Apenas camadas reativas.",
      "Camadas reativas e deliberativas para equilibrar rapidez e planeamento.",
      "Apenas raciocínio simbólico.",
      "Redes neuronais sem componente reativo.",
    ],
    correct: 1,
    exp: "Híbrida = camadas reativas para resposta rápida + camadas deliberativas para planeamento. Equilibra os dois mundos.",
  },
  {
    id: 7,
    topic: "sistemas_multi_agente",
    q: "Uma característica fundamental de um SMA é:",
    opts: [
      "Controlo global centralizado.",
      "Todos os agentes têm informação completa.",
      "Dados descentralizados e computação assíncrona.",
      "Agentes homogéneos obrigatórios.",
    ],
    correct: 2,
    exp: "SMA: sem controlo global, dados descentralizados, computação assíncrona, informação incompleta por agente.",
  },
  {
    id: 8,
    topic: "sistemas_multi_agente",
    q: "Ter demasiados agentes num SMA pode causar:",
    opts: [
      "Menor complexidade de coordenação.",
      "Sobrecarga de comunicação e maior complexidade de coordenação.",
      "Eliminação de conflitos.",
      "Processamento mais simples.",
    ],
    correct: 1,
    exp: "Mais agentes → mais mensagens, maior complexidade de coordenação e mais potenciais conflitos.",
  },
  {
    id: 9,
    topic: "sistemas_multi_agente",
    q: "Um SMA difere de um sistema distribuído convencional porque:",
    opts: [
      "Não usa rede.",
      "Os agentes trocam mensagens de alto nível com significado semântico e raciocinam sobre ações e objetivos.",
      "Não suporta concorrência.",
      "Todos os componentes executam o mesmo código.",
    ],
    correct: 1,
    exp: "Agentes comunicam com linguagens semânticas (ACL), raciocinam sobre objetivos e coordenam-se autonomamente.",
  },
  {
    id: 10,
    topic: "coordenacao",
    q: "A coordenação em SMA é necessária para:",
    opts: [
      "Eliminar a autonomia dos agentes.",
      "Garantir comportamento coerente da comunidade de agentes.",
      "Tornar todos os agentes iguais.",
      "Remover a necessidade de comunicação.",
    ],
    correct: 1,
    exp: "Coordenação = gerir dependências e ações para que o sistema se comporte de forma coerente.",
  },
  {
    id: 11,
    topic: "coordenacao",
    q: "Uma dependência de recurso partilhado ocorre quando:",
    opts: [
      "Agentes são completamente independentes.",
      "Múltiplos agentes precisam do mesmo recurso limitado.",
      "Apenas um agente existe no sistema.",
      "O ambiente é estático.",
    ],
    correct: 1,
    exp: "Recurso partilhado = sala de operações, caminho de robot, máquina — vários agentes precisam mas não podem usar simultaneamente.",
  },
  {
    id: 12,
    topic: "coordenacao",
    q: "Mesmo agentes cooperativos podem precisar de coordenação porque:",
    opts: [
      "Nunca competem por recursos.",
      "Podem competir por recursos, agir fora de ordem ou duplicar tarefas.",
      "Sempre têm informação completa.",
      "Não têm objetivos.",
    ],
    correct: 1,
    exp: "Cooperação não elimina conflitos de recursos, ordenação de tarefas ou trabalho duplicado.",
  },
  {
    id: 13,
    topic: "negociacao",
    q: "A primeira fase de um processo de negociação é:",
    opts: [
      "Acordo/fecho.",
      "Troca de propostas.",
      "Preparação/pré-negociação.",
      "Avaliação e concessão.",
    ],
    correct: 2,
    exp: "Fases: 1) Preparação 2) Troca de propostas 3) Avaliação/concessão 4) Acordo/fecho.",
  },
  {
    id: 14,
    topic: "negociacao",
    q: "No protocolo Contract Net, o passo inicial é:",
    opts: [
      "O contratante executa a tarefa.",
      "O gestor avalia propostas.",
      "O gestor envia um CFP (call for proposals).",
      "Os contratantes reportam resultados.",
    ],
    correct: 2,
    exp: "Contract Net: CFP → propostas → avaliação/adjudicação → execução → relatório de resultado.",
  },
  {
    id: 15,
    topic: "negociacao",
    q: "O Contract Net clássico NÃO é ideal para um leilão de peixe com descida de preço porque:",
    opts: [
      "O Contract Net não envolve propostas.",
      "O cenário tem rondas repetidas com descida de preço e compra parcial de lotes.",
      "O Contract Net só funciona com dois agentes.",
      "Leilões não envolvem negociação.",
    ],
    correct: 1,
    exp: "O mercado de peixe usa rondas descendentes de preço com compra parcial — mais próximo de um protocolo de leilão do que do Contract Net clássico.",
  },
  {
    id: 16,
    topic: "standards_plataformas",
    q: "As quatro áreas de interface FIPA são:",
    opts: [
      "Comunicação, Gestão, Integração Agente/Software, Interação Humano/Agente.",
      "TCP, UDP, HTTP, WebSocket.",
      "Java, Python, C++, Prolog.",
      "Input, Processing, Output, Storage.",
    ],
    correct: 0,
    exp: "FIPA define: Agent Communication, Agent Management, Agent/Software Integration, Human/Agent Interaction.",
  },
  {
    id: 17,
    topic: "standards_plataformas",
    q: "Um performativo numa mensagem ACL expressa:",
    opts: [
      "Apenas o formato dos dados.",
      "A intenção comunicativa da mensagem (ex: request, inform, cfp).",
      "O endereço IP do agente.",
      "O tamanho da mensagem.",
    ],
    correct: 1,
    exp: "Performativo = ato comunicativo. Define a intenção semântica: request, inform, cfp, accept-proposal, etc.",
  },
  {
    id: 18,
    topic: "standards_plataformas",
    q: "A diferença entre um facilitador e um broker é:",
    opts: [
      "São exatamente a mesma coisa.",
      "O facilitador ajuda a descobrir serviços; o broker medeia a interação entre consumidor e fornecedor.",
      "O broker apenas regista agentes.",
      "O facilitador executa tarefas pelos agentes.",
    ],
    correct: 1,
    exp: "Facilitador = descoberta de serviços. Broker = mediação da interação, recebe pedidos e encaminha/coordena com fornecedores.",
  },
  {
    id: 19,
    topic: "standards_plataformas",
    q: "A plataforma JADE distingue-se por:",
    opts: [
      "Ser escrita em Python e usar XMPP.",
      "Seguir as especificações FIPA, com containers, AMS e DF.",
      "Não suportar comunicação entre agentes.",
      "Ser exclusivamente para agentes reforço.",
    ],
    correct: 1,
    exp: "JADE = plataforma Java, FIPA-compliant, com containers, Agent Management System (AMS) e Directory Facilitator (DF).",
  },
  {
    id: 20,
    topic: "llm_marl",
    q: "Um agente LLM moderno tipicamente combina:",
    opts: [
      "Apenas regras gramaticais manuais.",
      "Motor cognitivo LLM, prompt/contexto, memória/RAG, ferramentas e orquestração.",
      "Apenas uma base de dados SQL.",
      "Sensores físicos e atuadores mecânicos.",
    ],
    correct: 1,
    exp: "Agente LLM = LLM + prompt + memória/RAG + ferramentas + orquestração de workflow + avaliação/feedback.",
  },
  {
    id: 21,
    topic: "llm_marl",
    q: "RAG (Retrieval-Augmented Generation) permite ao agente:",
    opts: [
      "Treinar novos pesos do modelo.",
      "Recuperar documentos/contexto externo relevante antes de gerar uma resposta.",
      "Eliminar a necessidade de prompt.",
      "Executar apenas código Python.",
    ],
    correct: 1,
    exp: "RAG = recuperar informação externa relevante e incorporá-la no contexto antes de gerar output.",
  },
  {
    id: 22,
    topic: "llm_marl",
    q: "MARL é aplicável quando o cenário tem:",
    opts: [
      "Um único agente sem interação.",
      "Interações repetidas, estados observáveis, ações e recompensas mensuráveis.",
      "Apenas dados estáticos sem feedback.",
      "Agentes que nunca aprendem.",
    ],
    correct: 1,
    exp: "MARL requer: ambiente com interações repetidas, estados, ações, recompensas e possibilidade de treino/simulação.",
  },
  {
    id: 23,
    topic: "negociacao",
    q: "Os estilos de resolução de conflito incluem:",
    opts: [
      "Apenas competição.",
      "Competição, colaboração, compromisso, evitação e acomodação.",
      "Apenas colaboração e evitação.",
      "Nenhum — conflitos não se resolvem.",
    ],
    correct: 1,
    exp: "Cinco estilos: competição, colaboração, compromisso, evitação, acomodação.",
  },
  {
    id: 24,
    topic: "agentes_ambientes",
    q: "A diferença entre reatividade e proatividade é:",
    opts: [
      "São sinónimos.",
      "Reatividade responde a mudanças; proatividade toma iniciativa para satisfazer objetivos.",
      "Proatividade é mais lenta que reatividade.",
      "Reatividade não envolve perceção.",
    ],
    correct: 1,
    exp: "Reatividade = responder a mudanças percebidas. Proatividade = tomar iniciativa orientada a objetivos.",
  },
  {
    id: 25,
    topic: "arquiteturas",
    q: "Ao responder a uma pergunta de exame sobre BDI, deve-se:",
    opts: [
      "Apenas nomear BDI sem instanciar.",
      "Instanciar com crenças, desejos e intenções concretos do cenário.",
      "Descrever apenas a arquitetura reativa.",
      "Ignorar o cenário dado.",
    ],
    correct: 1,
    exp: "Em exame, não basta nomear BDI. Deve-se instanciar: crenças concretas, desejos concretos e intenções concretas do cenário.",
  },
];

export const SIMAGIA_TOPIC_LABELS: Record<string, string> = {
  agentes_ambientes: "Agentes e Ambientes",
  arquiteturas: "Arquiteturas",
  sistemas_multi_agente: "Sistemas Multi-Agente",
  coordenacao: "Coordenação",
  negociacao: "Negociação",
  standards_plataformas: "Standards e Plataformas",
  llm_marl: "LLM Agents e MARL",
};

export const SIMAGIA_SECTIONS: Section[] = [
  {
    id: "inicio",
    num: "00",
    title: "Visão Geral",
    subtitle: "Guia de estudo SIMAGIA",
  },
  {
    id: "agentes_ambientes",
    num: "01",
    title: "Agentes e Ambientes",
    subtitle: "Fundamentos, noção fraca/forte e tipos de ambiente",
  },
  {
    id: "arquiteturas",
    num: "02",
    title: "Arquiteturas de Agentes",
    subtitle: "Deliberativa, reativa, híbrida e BDI",
  },
  {
    id: "sistemas_multi_agente",
    num: "03",
    title: "Sistemas Multi-Agente",
    subtitle: "Conceito, características e desafios",
  },
  {
    id: "coordenacao",
    num: "04",
    title: "Coordenação",
    subtitle: "Dependências, cooperação e conflito",
  },
  {
    id: "negociacao",
    num: "05",
    title: "Negociação e Contract Net",
    subtitle: "Fases, protocolos e adequação",
  },
  {
    id: "standards_plataformas",
    num: "06",
    title: "Standards e Plataformas",
    subtitle: "FIPA, ACL, KQML, JADE e SPADE",
  },
  {
    id: "llm_marl",
    num: "07",
    title: "Agentes LLM e MARL",
    subtitle: "LLMs, tool calling, RAG e aprendizagem multi-agente",
  },
  {
    id: "assessment",
    num: "08",
    title: "Avaliação Final",
    subtitle: "Teste prático estilo exame",
  },
  {
    id: "answer_key",
    num: "09",
    title: "Chave de Respostas",
    subtitle: "Respostas consolidadas e templates",
  },
  {
    id: "simulado",
    num: "∞",
    title: "Simulado Final",
    subtitle: "25 questões estilo prova",
  },
];
