import type { Question, Section } from "@/lib/data";

export const TRANSFORMER_QUESTIONS: Question[] = [
  {
    id: 1,
    topic: "overview",
    q: "A principal inovação da arquitetura Transformer em relação às RNNs é:",
    opts: [
      "Usar apenas Bag of Words para representar frases.",
      "Substituir o processamento sequencial por mecanismos de atenção, permitindo maior paralelização.",
      "Eliminar completamente a necessidade de embeddings.",
      "Usar apenas regras gramaticais manuais.",
    ],
    correct: 1,
    exp: "Vaswani et al. (2017): jogar fora a recorrência e construir tudo a partir de atenção. Sem dependência sequencial → paralelização massiva no treino.",
  },
  {
    id: 2,
    topic: "self_attention",
    q: "O mecanismo de self-attention permite ao Transformer:",
    opts: [
      "Capturar relações entre palavras dentro da mesma sequência.",
      "Capturar apenas relações entre documentos diferentes.",
      "Remover automaticamente stop words.",
      "Traduzir palavras sem considerar contexto.",
    ],
    correct: 0,
    exp: "Self-attention = atenção que cada token presta nos demais tokens da MESMA sequência. É o que substitui a recorrência.",
  },
  {
    id: 3,
    topic: "self_attention",
    q: "O termo intra-attention refere-se a:",
    opts: [
      "Atenção aplicada dentro de uma mesma sequência.",
      "Atenção aplicada apenas entre sequência de entrada e sequência de saída.",
      "Atenção usada somente em imagens.",
      "Atenção aplicada depois da camada softmax final.",
    ],
    correct: 0,
    exp: "Intra-attention é sinônimo de self-attention. \"Intra\" = dentro. Mesma sequência olhando para si mesma.",
  },
  {
    id: 4,
    topic: "enc_dec_attention",
    q: "O termo inter-attention refere-se a:",
    opts: [
      "Relações dentro de uma única sequência.",
      "Relações entre duas sequências, como entrada e saída.",
      "Relações entre palavras raras e stop words.",
      "Relações apenas entre documentos do corpus.",
    ],
    correct: 1,
    exp: "Inter-attention = entre duas sequências distintas. No Transformer, é a encoder-decoder attention (decoder olha para a saída do encoder).",
  },
  {
    id: 5,
    topic: "self_attention",
    q: "A diferença correta entre intra-attention e inter-attention é:",
    opts: [
      "Intra-attention modela relações dentro da mesma sequência; inter-attention modela relações entre sequências diferentes.",
      "Intra-attention modela relações entre sequências diferentes; inter-attention modela relações dentro da mesma sequência.",
      "Ambas modelam apenas relações dentro da sequência de entrada.",
      "Ambas são usadas apenas em CNNs.",
    ],
    correct: 0,
    exp: "Pegadinha clássica. Intra = dentro (self-attention). Inter = entre (enc-dec attention). Decorar.",
  },
  {
    id: 6,
    topic: "enc_dec_attention",
    q: "No Transformer, a encoder-decoder attention permite que:",
    opts: [
      "O decoder foque em partes relevantes da sequência de entrada.",
      "O encoder ignore completamente a sequência de entrada.",
      "O modelo remova a necessidade de positional encoding.",
      "O modelo use Bag of Words em vez de embeddings.",
    ],
    correct: 0,
    exp: "É o equivalente à atenção de Bahdanau dentro do Transformer: a cada passo, o decoder consulta a representação do encoder.",
  },
  {
    id: 7,
    topic: "enc_dec_attention",
    q: "Na encoder-decoder attention, normalmente:",
    opts: [
      "As Queries vêm do decoder, enquanto Keys e Values vêm da saída do encoder.",
      "Queries, Keys e Values vêm apenas da sequência de entrada original.",
      "Queries vêm do vocabulário e Values vêm do TF-IDF.",
      "Keys e Values são sempre vetores binários.",
    ],
    correct: 0,
    exp: "Q do decoder pergunta \"o que é relevante?\", K/V vêm do encoder e respondem. Diferente da self-attention, onde Q, K e V vêm da mesma fonte.",
  },
  {
    id: 8,
    topic: "multi_head",
    q: "O objetivo da multi-head attention é:",
    opts: [
      "Capturar diferentes tipos de relações contextuais entre palavras.",
      "Reduzir o modelo a uma única cabeça de atenção.",
      "Substituir embeddings por one-hot encoding.",
      "Impedir o uso de softmax.",
    ],
    correct: 0,
    exp: "Cabeças paralelas em subespaços diferentes — cada uma especializa em um tipo de relação (sintática, semântica, posicional, etc).",
  },
  {
    id: 9,
    topic: "multi_head",
    q: "Em multi-head attention, várias cabeças de atenção são úteis porque:",
    opts: [
      "Cada cabeça pode aprender a focar em padrões ou relações diferentes.",
      "Todas as cabeças aprendem obrigatoriamente a mesma relação.",
      "As cabeças servem apenas para aumentar o tamanho do vocabulário.",
      "Elas eliminam a necessidade de treino supervisionado.",
    ],
    correct: 0,
    exp: "Diversidade de focos. Análises de atenção em modelos treinados mostram cabeças \"sintáticas\", \"co-referência\", \"posicionais\", etc.",
  },
  {
    id: 10,
    topic: "multi_head",
    q: "Depois de calcular várias cabeças de atenção, o Transformer normalmente:",
    opts: [
      "Concatena os resultados e aplica uma matriz de projeção.",
      "Escolhe aleatoriamente apenas uma cabeça.",
      "Descarta todas as cabeças menos a primeira.",
      "Transforma cada cabeça em uma palavra diretamente.",
    ],
    correct: 0,
    exp: "MultiHead(Q,K,V) = Concat(head_1,...,head_h) · W_O. A matriz W_O reprojeta para a dimensão do modelo.",
  },
  {
    id: 11,
    topic: "positional",
    q: "O positional encoding é necessário porque:",
    opts: [
      "O Transformer processa tokens em paralelo e precisa de informação sobre a ordem das palavras.",
      "O Transformer é uma RNN e por isso esquece a posição das palavras.",
      "O positional encoding serve para remover palavras raras.",
      "O positional encoding substitui completamente os embeddings.",
    ],
    correct: 0,
    exp: "Sem recorrência, sem ordem implícita. O modelo veria \"o gato comeu\" e \"comeu gato o\" como conjuntos iguais sem PE.",
  },
  {
    id: 12,
    topic: "positional",
    q: "O positional encoding é adicionado:",
    opts: [
      "Aos embeddings dos tokens, para incorporar informação de posição.",
      "Apenas ao vetor final do softmax.",
      "Apenas à matriz de pesos da regressão logística.",
      "Apenas às stop words.",
    ],
    correct: 0,
    exp: "input = embedding(token) + PE(posição). Soma componente-a-componente, antes do primeiro bloco.",
  },
  {
    id: 13,
    topic: "positional",
    q: "Sobre positional encoding, assinale a alternativa correta:",
    opts: [
      "Serve para aproximar palavras semanticamente parecidas no espaço vetorial.",
      "Serve para informar a posição dos tokens na sequência.",
      "Serve para calcular TF-IDF.",
      "Serve para remover o decoder.",
    ],
    correct: 1,
    exp: "Pegadinha: PE NÃO trata semântica. Isso é trabalho dos embeddings. PE só carrega ordem/posição.",
  },
  {
    id: 14,
    topic: "positional",
    q: "A afirmação “o Transformer não precisa de positional encoding porque processa sequências de forma recorrente” é:",
    opts: [
      "Verdadeira.",
      "Falsa, porque o Transformer não é recorrente e precisa de informação posicional explícita.",
      "Verdadeira apenas no decoder.",
      "Verdadeira apenas em tradução automática.",
    ],
    correct: 1,
    exp: "Pegadinha de afirmação dupla. Transformer não é recorrente — precisamente por isso o PE é obrigatório.",
  },
  {
    id: 15,
    topic: "layer_norm",
    q: "A layer normalization no Transformer tem como principal função:",
    opts: [
      "Estabilizar e acelerar o treino, normalizando ativações nas camadas.",
      "Reduzir o vocabulário de saída.",
      "Transformar embeddings densos em esparsos.",
      "Substituir o mecanismo de atenção.",
    ],
    correct: 0,
    exp: "LayerNorm centra/escala ativações por amostra (não por batch). Estabiliza distribuições internas e melhora a convergência.",
  },
  {
    id: 16,
    topic: "layer_norm",
    q: "As conexões residuais no Transformer ajudam a:",
    opts: [
      "Facilitar o fluxo de gradientes e o treino de redes profundas.",
      "Eliminar a necessidade de embeddings.",
      "Transformar a tarefa em Bag of Words.",
      "Remover a sequência de saída.",
    ],
    correct: 0,
    exp: "Skip connections (input + sublayer(input)) — atalho para o gradiente, herdado dos ResNets. Sem elas, treinar 6+ camadas seria miserável.",
  },
  {
    id: 17,
    topic: "architecture",
    q: "No encoder do Transformer, cada bloco normalmente contém:",
    opts: [
      "Self-attention e uma rede feed-forward.",
      "Apenas uma camada softmax.",
      "Apenas uma LSTM.",
      "Apenas uma matriz TF-IDF.",
    ],
    correct: 0,
    exp: "Bloco encoder = Multi-Head Self-Attention → Add&Norm → FFN → Add&Norm. Repete N vezes (geralmente 6).",
  },
  {
    id: 18,
    topic: "architecture",
    q: "No decoder do Transformer, existe:",
    opts: [
      "Masked self-attention, encoder-decoder attention e feed-forward network.",
      "Apenas Bag of Words.",
      "Apenas SVD.",
      "Apenas uma camada de stemming.",
    ],
    correct: 0,
    exp: "Bloco decoder tem três sublayers: Masked SA → Enc-Dec Attention → FFN. Cada um com Add&Norm.",
  },
  {
    id: 19,
    topic: "masked",
    q: "O decoder masking é usado para:",
    opts: [
      "Impedir que o decoder olhe para tokens futuros durante a geração.",
      "Impedir que o encoder veja a sequência de entrada.",
      "Remover tokens desconhecidos do vocabulário.",
      "Normalizar os embeddings.",
    ],
    correct: 0,
    exp: "Causal mask: posições futuras recebem -∞ antes do softmax → α=0. Garante que y_t só dependa de y_<t.",
  },
  {
    id: 20,
    topic: "masked",
    q: "No masked self-attention do decoder, as posições futuras são mascaradas para:",
    opts: [
      "Preservar o comportamento autoregressivo da geração.",
      "Aumentar artificialmente o tamanho do vocabulário.",
      "Criar embeddings estáticos.",
      "Aplicar stemming nas palavras futuras.",
    ],
    correct: 0,
    exp: "Sem máscara, o modelo veria a resposta durante o treino — trapaça. Com máscara, treino e inferência se alinham.",
  },
  {
    id: 21,
    topic: "enc_dec_attention",
    q: "A saída do último encoder no Transformer:",
    opts: [
      "É usada pelos decoders na camada de encoder-decoder attention.",
      "É descartada antes de chegar ao decoder.",
      "Alimenta apenas o primeiro token da saída.",
      "Serve apenas para calcular TF-IDF.",
    ],
    correct: 0,
    exp: "A representação final do encoder vira K/V para a enc-dec attention de TODOS os blocos do decoder. Daí cada um \"olha\" para a entrada.",
  },
  {
    id: 22,
    topic: "masked",
    q: "Na arquitetura Transformer clássica, o decoder gera a sequência:",
    opts: [
      "Um token por vez, usando tokens anteriores e atenção sobre a saída do encoder.",
      "Toda de uma vez sem considerar tokens anteriores.",
      "Apenas por contagem de palavras.",
      "Apenas usando stop words.",
    ],
    correct: 0,
    exp: "Inferência é autoregressiva: y_t = f(y_<t, encoder_out). No treino há paralelização via teacher forcing + máscara.",
  },
  {
    id: 23,
    topic: "output",
    q: "A camada final linear + softmax do decoder serve para:",
    opts: [
      "Transformar o vetor produzido pelo decoder em probabilidades sobre o vocabulário.",
      "Calcular a posição dos tokens na entrada.",
      "Fazer o alinhamento manual entre frases.",
      "Reduzir a matriz de coocorrência.",
    ],
    correct: 0,
    exp: "Linear: R^d_model → R^|V|. Softmax: logits → distribuição de probabilidade sobre o vocabulário.",
  },
  {
    id: 24,
    topic: "output",
    q: "Sobre a função softmax no decoder do Transformer, é correto afirmar que:",
    opts: [
      "Produz probabilidades positivas que somam 1.",
      "Produz sempre valores binários.",
      "Produz apenas valores negativos.",
      "Não depende do vocabulário de saída.",
    ],
    correct: 0,
    exp: "softmax(z)_i = exp(z_i)/Σexp(z_j). Por construção: positivo, soma 1. Tamanho da saída = |V|.",
  },
  {
    id: 25,
    topic: "overview",
    q: "Qual alternativa descreve melhor o funcionamento geral do Transformer?",
    opts: [
      "Usa self-attention, feed-forward networks, positional encoding, conexões residuais e normalização para processar sequências sem recorrência.",
      "Usa apenas RNNs e não permite processamento paralelo.",
      "Usa somente Bag of Words e regressão logística.",
      "Usa apenas regras linguísticas manuais.",
    ],
    correct: 0,
    exp: "Receita completa: SA + FFN + PE + residual + LayerNorm. Tudo sem recorrência. É a alternativa-síntese.",
  },
];

export const TRANSFORMER_TOPIC_LABELS: Record<string, string> = {
  overview: "Visão Geral",
  self_attention: "Self-Attention",
  enc_dec_attention: "Enc-Dec Attention",
  multi_head: "Multi-Head",
  positional: "Positional Encoding",
  layer_norm: "Layer Norm & Residual",
  architecture: "Arquitetura",
  masked: "Masked Attention",
  output: "Saída & Softmax",
};

export const TRANSFORMER_SECTIONS: Section[] = [
  {
    id: "inicio",
    num: "00",
    title: "Visão Geral",
    subtitle: "Attention is all you need",
  },
  {
    id: "self_attention",
    num: "01",
    title: "Self-Attention",
    subtitle: "Intra-attention — relações na mesma sequência",
  },
  {
    id: "enc_dec_attention",
    num: "02",
    title: "Encoder-Decoder Attention",
    subtitle: "Inter-attention — entrada conversa com saída",
  },
  {
    id: "multi_head",
    num: "03",
    title: "Multi-Head Attention",
    subtitle: "Várias cabeças, múltiplos focos",
  },
  {
    id: "positional",
    num: "04",
    title: "Positional Encoding",
    subtitle: "Reintroduzindo a noção de ordem",
  },
  {
    id: "layer_norm",
    num: "05",
    title: "Layer Norm & Residual",
    subtitle: "Estabilizando treino profundo",
  },
  {
    id: "architecture",
    num: "06",
    title: "Arquitetura",
    subtitle: "Blocos do encoder e do decoder",
  },
  {
    id: "masked",
    num: "07",
    title: "Masked Attention",
    subtitle: "O decoder não vê o futuro",
  },
  {
    id: "output",
    num: "08",
    title: "Saída & Softmax",
    subtitle: "Logits viram probabilidades sobre o vocabulário",
  },
  {
    id: "simulado",
    num: "∞",
    title: "Simulado Final",
    subtitle: "25 questões estilo prova",
  },
];
