import { createContext, useContext } from "react";

/**
 * Interface text for the lesson chrome, in the course's own language, so an English
 * caderno never shows Portuguese buttons (and vice versa). CoursePage sets the language.
 */
export const UI_TEXT = {
  pt: {
    courses: "Cursos",
    breadcrumb: "Caminho",
    showChapters: "Mostrar capítulos",
    hideChapters: "Esconder capítulos",
    openChapters: "Abrir capítulos",
    exitToCourses: "Sair para os cursos",
    navigation: "Navegação",
    chapters: "Capítulos",
    chapter: "Capítulo",
    chapterShort: "cap.",
    chapterOf: (index: number, total: number) => `Capítulo ${index} de ${total}`,
    notebook: "caderno",
    progress: "Progresso",
    chapterSteps: "Etapas do capítulo",
    back: "Voltar",
    continue: "Continuar",
    nextChapter: "Próximo capítulo",
    skip: "Saltar",
    answerFirst: "Responde à pergunta acima — ou salta.",
    part: (shown: number, total: number) => `Parte ${shown} de ${total}`,
    start: "Começar",
    upNext: "A seguir:",
    stepOf: (index: number, total: number) => `etapa ${index} de ${total}`,
    endTitle: "Fim do caderno",
    visited: (seen: number, total: number) => `${seen}/${total} capítulos visitados.`,
    backToCourses: "Voltar aos cursos",
    goals: "Objetivos deste capítulo",
    done: "Concluído",
    flashTo: (back: boolean) => `tocar para ver a ${back ? "pergunta" : "resposta"}`,
    next: "seguinte",
    finish: "concluir",
    repeat: "repetir",
    matchItem: "item a associar",
    matchRight: "Certo. Segue para o próximo.",
    matchWrong: "Ainda não. Escolhe a opção que corresponde melhor a este item.",
    matchDone: "Associação concluída. Repetir uma vez mais ajuda a fixar.",
    noQuestions: "Sem perguntas configuradas para este checkpoint.",
    noPairs: "Sem pares configurados para esta associação.",
    checkpointKicker: "quiz de checkpoint",
    quiz: {
      check: "Verificar",
      next: "Continuar",
      finish: "Ver resultado",
      correct: "Correto!",
      wrong: "Ainda não",
      retry: "Repetir",
      perfect: "Perfeito — domínio total.",
      good: "Bom trabalho — e todos os erros corrigidos na segunda volta.",
      review: "Tudo corrigido no fim, mas vale a pena reler o capítulo.",
      fixKicker: "corrige os erros",
      fixLeft: (left: number) => `${left} por corrigir`,
    },
    exam: {
      progress: "progresso",
      submit: "Submeter",
      next: "Seguinte",
      review: "Rever respostas",
      toResult: "Ver resultado",
      retry: "Refazer",
      result: "resultado",
      byTopic: "por tópico",
      grades: ["excelente", "muito bom", "passou, mas revise", "repita os tópicos fracos"],
    },
  },
  en: {
    courses: "Courses",
    breadcrumb: "Breadcrumb",
    showChapters: "Show chapters",
    hideChapters: "Hide chapters",
    openChapters: "Open chapters",
    exitToCourses: "Exit to courses",
    navigation: "Navigation",
    chapters: "Chapters",
    chapter: "Chapter",
    chapterShort: "ch.",
    chapterOf: (index: number, total: number) => `Chapter ${index} of ${total}`,
    notebook: "notebook",
    progress: "Progress",
    chapterSteps: "Chapter steps",
    back: "Back",
    continue: "Continue",
    nextChapter: "Next chapter",
    skip: "Skip",
    answerFirst: "Answer the question above — or skip it.",
    part: (shown: number, total: number) => `Part ${shown} of ${total}`,
    start: "Start",
    upNext: "Up next:",
    stepOf: (index: number, total: number) => `step ${index} of ${total}`,
    endTitle: "End of the notebook",
    visited: (seen: number, total: number) => `${seen}/${total} chapters visited.`,
    backToCourses: "Back to courses",
    goals: "Chapter goals",
    done: "Done",
    flashTo: (back: boolean) => `tap for the ${back ? "question" : "answer"}`,
    next: "next",
    finish: "finish",
    repeat: "repeat",
    matchItem: "match this",
    matchRight: "Right. On to the next one.",
    matchWrong: "Not quite. Pick the option that fits this item best.",
    matchDone: "All matched. One more round makes it stick.",
    noQuestions: "No questions configured for this checkpoint.",
    noPairs: "No pairs configured for this drill.",
    checkpointKicker: "checkpoint quiz",
    quiz: {
      check: "Check",
      next: "Continue",
      finish: "See result",
      correct: "Correct!",
      wrong: "Not quite",
      retry: "Retry",
      perfect: "Perfect — full marks.",
      good: "Nice work — and every miss fixed on the second pass.",
      review: "All fixed in the end, but the chapter is worth a re-read.",
      fixKicker: "fix your mistakes",
      fixLeft: (left: number) => `${left} to fix`,
    },
    exam: {
      progress: "progress",
      submit: "Submit",
      next: "Next",
      review: "Review answers",
      toResult: "See result",
      retry: "Retry",
      result: "result",
      byTopic: "by topic",
      grades: ["excellent", "very good", "passed — review the misses", "repeat the weak topics"],
    },
  },
} as const;

export type Lang = keyof typeof UI_TEXT;

export const LangContext = createContext<Lang>("pt");

export const useUiText = () => UI_TEXT[useContext(LangContext)];
