import type { Question, Section } from "@/lib/data";

export const WORLD_MODELS_QUESTIONS: Question[] = [
  {
    id: 1,
    topic: "overview",
    q: "The fundamental difference between a classifier and a world model is:",
    opts: [
      "The classifier uses neural networks and the world model uses statistical rules.",
      "The classifier maps input to a human-provided label; the world model predicts missing or future parts of its own input.",
      "The world model only works with video, the classifier only with images.",
      "The world model does not need training.",
    ],
    correct: 1,
    exp: "Classifier = supervised mapping input → label. World model = self-supervised prediction, where the target comes from the data itself.",
  },
  {
    id: 2,
    topic: "overview",
    q: "Why is self-supervised learning attractive at scale?",
    opts: [
      "Because it requires no data.",
      "Because it always achieves higher accuracy than supervised learning.",
      "Because the supervision signal comes from the data itself, allowing training on huge unlabeled corpora.",
      "Because it eliminates the need for GPUs.",
    ],
    correct: 2,
    exp: "The bottleneck in supervised learning is human labeling. Self-supervision removes it — frame 9 is already in the video.",
  },
  {
    id: 3,
    topic: "overview",
    q: "After pretraining a world model, what is normally reused for the real task?",
    opts: [
      "The predicted frames.",
      "The loss function.",
      "The learned representation (the encoder's output).",
      "The training dataset.",
    ],
    correct: 2,
    exp: "The prediction is a disposable pretext. The prize is the representation the encoder built in order to predict.",
  },
  {
    id: 4,
    topic: "overview",
    q: "Which statement is FALSE about world models?",
    opts: [
      "They learn notions like object permanence without anyone labeling them.",
      "By definition they must generate realistic pixels.",
      "They can be trained on unlabeled video.",
      "The term was popularized by Ha & Schmidhuber (2018).",
    ],
    correct: 1,
    exp: "Pixel generation is one option, not the definition. JEPA predicts in representation space and never reconstructs pixels.",
  },
  {
    id: 5,
    topic: "ingredients",
    q: "In a world model, the 'context' and the 'target' are:",
    opts: [
      "The input and its human-written label.",
      "The encoder and the predictor.",
      "The training set and the test set.",
      "Two parts of the same input: the visible part and the hidden part.",
    ],
    correct: 3,
    exp: "Both come from the same clip. The mask decides which part is visible (context) and which is hidden (target). No human label is involved.",
  },
  {
    id: 6,
    topic: "ingredients",
    q: "What is the job of the predictor?",
    opts: [
      "Turn raw pixels into a representation vector.",
      "Decide which patches to hide.",
      "Guess the target from the context's representation and the target's position.",
      "Compute the gradient of the loss.",
    ],
    correct: 2,
    exp: "The predictor is the 'imagination': given what was seen and where the hidden part is, it guesses what the hidden part contains.",
  },
  {
    id: 7,
    topic: "ingredients",
    q: "After pretraining, which component is normally kept for downstream tasks?",
    opts: [
      "The predictor.",
      "The mask.",
      "The loss function.",
      "The encoder.",
    ],
    correct: 3,
    exp: "The encoder learned to see and summarize — that's the reusable part. The predictor was scaffolding for the training game. (Even for planning, V-JEPA 2 trains a new action-conditioned predictor on the frozen encoder.)",
  },
  {
    id: 8,
    topic: "ingredients",
    q: "Which design decision determines whether a model is pixel-predicting or latent-predicting (JEPA-style)?",
    opts: [
      "The number of encoder layers.",
      "What the loss compares the prediction against: raw pixels or representations.",
      "Whether the data is video or images.",
      "The learning rate.",
    ],
    correct: 1,
    exp: "The loss target is the key choice. Compare against pixels → pixel prediction. Compare against the target's representation → latent prediction (JEPA).",
  },
  // ── 02 · pixel vs latent ──
  {
    id: 9,
    topic: "pixel_latent",
    q: "A pixel-prediction model trained with squared error predicts blurry futures mainly because:",
    opts: [
      "Its network is too small.",
      "Under uncertainty, the prediction that minimises squared error is the average of the possible futures.",
      "Video frames are compressed.",
      "It was trained for too few epochs.",
    ],
    correct: 1,
    exp: "With several possible futures, MSE is minimised by their mean. The mean of sharp images is a blurry image — blur is the optimum, not a bug.",
  },
  {
    id: 10,
    topic: "pixel_latent",
    q: "Why does a pixel loss waste model capacity?",
    opts: [
      "It forces the model to predict unpredictable detail such as leaf texture and sensor noise.",
      "It uses too much GPU memory.",
      "It can't be backpropagated.",
      "It only works on images, not video.",
    ],
    correct: 0,
    exp: "Every pixel counts in the loss, including chaotic detail no model can foresee. Capacity goes into noise instead of what matters.",
  },
  {
    id: 11,
    topic: "pixel_latent",
    q: "In a Joint-Embedding Predictive Architecture, the target the predictor must match is:",
    opts: [
      "The target encoder's representation of the hidden region.",
      "A human-written label.",
      "The raw pixels of the hidden region.",
      "A random vector.",
    ],
    correct: 0,
    exp: "Both context and target are embedded by encoders; the predictor maps the context embedding to the target embedding.",
  },
  {
    id: 12,
    topic: "pixel_latent",
    q: "In the V-JEPA paper's comparison (same data, schedule and masking; frozen evaluation), predicting features instead of pixels:",
    opts: [
      "Made no difference.",
      "Was worse on every benchmark.",
      "Improved results, e.g. 73.7% vs 68.6% on Kinetics-400.",
      "Only helped on ImageNet.",
    ],
    correct: 2,
    exp: "Feature prediction won on K400 (73.7 vs 68.6) and ImageNet (74.8 vs 73.3) and tied on SSv2 (66.2 vs 66.0). The runs shared data, schedule and masking; the target and its loss differed.",
  },
  // ── 03 · collapse ──
  {
    id: 13,
    topic: "collapse",
    q: "Representation collapse is when:",
    opts: [
      "The encoder maps every input to (nearly) the same vector, making the loss trivially low.",
      "The model runs out of memory.",
      "The loss explodes to infinity.",
      "The model overfits the training set.",
    ],
    correct: 0,
    exp: "If both sides are learned, a constant output makes prediction = target for free. Zero loss, zero information.",
  },
  {
    id: 14,
    topic: "collapse",
    q: "Why can't a pixel-reconstruction model collapse in the same way?",
    opts: [
      "Because it uses a bigger encoder.",
      "Because its target — the real pixels — is fixed data the model cannot change.",
      "Because it uses negatives.",
      "Because it has no loss function.",
    ],
    correct: 1,
    exp: "Collapse needs a movable target. Pixels are data, not a model output, so the target can't be made trivial.",
  },
  {
    id: 15,
    topic: "collapse",
    q: "Which anti-collapse strategy do I-JEPA and V-JEPA use?",
    opts: [
      "Contrastive learning with many negatives.",
      "VICReg variance and covariance penalties.",
      "Asymmetry: a predictor on one side, stop-gradient and an EMA target encoder on the other.",
      "Pixel reconstruction as an auxiliary loss.",
    ],
    correct: 2,
    exp: "They inherit BYOL-style asymmetry: predictor + stop-grad + EMA target. No negatives needed.",
  },
  {
    id: 16,
    topic: "collapse",
    q: "Which signal in your training logs is the clearest warning of collapse?",
    opts: [
      "The per-dimension standard deviation of the embeddings drops toward zero.",
      "The learning rate warms up.",
      "GPU utilisation is high.",
      "Validation accuracy goes up.",
    ],
    correct: 0,
    exp: "Collapsed embeddings have no spread. Tracking per-dimension std across a batch (plus an occasional linear probe) catches it early.",
  },
  // ── 04 · family tree ──
  {
    id: 17,
    topic: "family",
    q: "In Ha & Schmidhuber's World Models (2018), the three components are:",
    opts: [
      "V (a VAE), M (an MDN-RNN that predicts the next latent), and C (a small controller).",
      "Encoder, predictor, loss.",
      "Context encoder, target encoder, predictor.",
      "Generator, discriminator, critic.",
    ],
    correct: 0,
    exp: "V compresses frames, M predicts how the compressed state evolves, C acts. In VizDoom the controller was even trained entirely inside the model's dream.",
  },
  {
    id: 18,
    topic: "family",
    q: "Which of these learns by reconstructing pixels rather than predicting representations?",
    opts: ["BYOL", "I-JEPA", "MAE", "V-JEPA"],
    correct: 2,
    exp: "MAE masks 75% of patches and reconstructs their pixels. The others predict representations.",
  },
  {
    id: 19,
    topic: "family",
    q: "What did JEPA inherit from BYOL?",
    opts: [
      "Pixel reconstruction.",
      "The tubelet embedding.",
      "The VAE encoder.",
      "Learning without negatives via an EMA target network and an online predictor.",
    ],
    correct: 3,
    exp: "BYOL showed that an EMA target plus a predictor (with stop-gradient) avoids collapse without negatives.",
  },
  {
    id: 20,
    topic: "family",
    q: "LeCun's 2022 paper 'A Path Towards Autonomous Machine Intelligence' is best described as:",
    opts: [
      "A trained video model that beat Kinetics-400.",
      "A position paper proposing JEPA (and hierarchical H-JEPA) as the world model at the core of an agent.",
      "A dataset paper.",
      "A robotics benchmark.",
    ],
    correct: 1,
    exp: "It's a proposal, not a trained model. I-JEPA (2023) was the first model built under the JEPA name.",
  },
  // ── 05 · I-JEPA ──
  {
    id: 21,
    topic: "ijepa",
    q: "I-JEPA's masking strategy uses:",
    opts: [
      "4 target blocks of 15–20% of the image each, and one large context block (85–100%) with the targets removed.",
      "One small target and a tiny context.",
      "Random single pixels.",
      "The whole image as both context and target.",
    ],
    correct: 0,
    exp: "Large targets make the task semantic; a large, spread-out context makes it informative. Overlaps are removed so answers can't leak.",
  },
  {
    id: 22,
    topic: "ijepa",
    q: "In I-JEPA, the target representations are obtained by:",
    opts: [
      "Feeding only the target patches into the target encoder.",
      "Running the target encoder on the full image and selecting the target blocks from its output.",
      "Reconstructing the target pixels.",
      "Averaging the context tokens.",
    ],
    correct: 1,
    exp: "Masking the output (not the input) gives context-aware, high-level targets — the paper calls this crucial.",
  },
  {
    id: 23,
    topic: "ijepa",
    q: "What does the I-JEPA predictor receive as input?",
    opts: [
      "The full image.",
      "A class label.",
      "Only the target encoder's output.",
      "The context encoder's tokens plus mask tokens (with positional embeddings) for one target block — it runs once per block.",
    ],
    correct: 3,
    exp: "The mask tokens tell the predictor WHERE to predict; the context tokens tell it WHAT it has seen.",
  },
  {
    id: 24,
    topic: "ijepa",
    q: "How is I-JEPA's target encoder updated?",
    opts: [
      "By backpropagation, like the context encoder.",
      "As an exponential moving average of the context encoder, with momentum ramping from 0.996 to 1.0.",
      "It is frozen at initialisation.",
      "It is copied from a pretrained supervised model.",
    ],
    correct: 1,
    exp: "No gradients reach the target encoder. It slowly follows the context encoder via EMA, becoming a steady teacher.",
  },
  // ── 06 · V-JEPA ──
  {
    id: 25,
    topic: "vjepa",
    q: "V-JEPA embeds a 16-frame 224×224 clip with 2×16×16 tubelets. How many tokens is that?",
    opts: ["196", "784", "1,568", "3,136"],
    correct: 2,
    exp: "(16 ÷ 2) × (224 ÷ 16)² = 8 × 14 × 14 = 1,568 tokens.",
  },
  {
    id: 26,
    topic: "vjepa",
    q: "Why does V-JEPA repeat the same spatial mask across all frames of the clip?",
    opts: [
      "To save memory.",
      "To stop the model copying a hidden patch from the same spot in a neighbouring frame.",
      "Because the loss requires it.",
      "To make training faster.",
    ],
    correct: 1,
    exp: "Consecutive frames are nearly identical. Per-frame masks leak the answer; tube masks close that shortcut.",
  },
  {
    id: 27,
    topic: "vjepa",
    q: "Roughly what fraction of the video does V-JEPA's multi-block masking hide?",
    opts: ["About 15%", "About 50%", "About 75%", "About 90%"],
    correct: 3,
    exp: "Each clip gets two masks — short-range (union of 8 blocks of ~15%) and long-range (union of 2 blocks of ~70%) — trained as separate prediction tasks, for an average masking ratio of ~90%. Video is so redundant that lighter masking is too easy.",
  },
  {
    id: 28,
    topic: "vjepa",
    q: "Which is NOT one of V-JEPA 2's changes compared with V-JEPA?",
    opts: [
      "Over 1M hours of pretraining video.",
      "A ViT-g encoder with over 1B parameters.",
      "3D-RoPE position embeddings.",
      "Switching back to predicting pixels.",
    ],
    correct: 3,
    exp: "V-JEPA 2 still predicts features. It scales data and model size, adds 3D-RoPE and a progressive-resolution recipe.",
  },
  // ── 07 · usage ──
  {
    id: 29,
    topic: "usage",
    q: "What is 'frozen evaluation'?",
    opts: [
      "Keeping the pretrained encoder's weights fixed and training only a small head (probe) on top.",
      "Evaluating on a frozen dataset that never changes.",
      "Evaluating without any training at all.",
      "Fine-tuning at a low temperature.",
    ],
    correct: 0,
    exp: "Only the probe learns. It measures what the encoder learned by itself — the fair test of a world model.",
  },
  {
    id: 30,
    topic: "usage",
    q: "An attentive probe works by:",
    opts: [
      "Averaging all tokens and applying a linear layer.",
      "Unfreezing the last encoder block.",
      "Adding a CLS token to the encoder and retraining it.",
      "A learnable query token cross-attending over all patch tokens, followed by a small MLP.",
    ],
    correct: 3,
    exp: "The learned query decides which tokens matter for the task. It's V-JEPA's standard frozen evaluation (V-JEPA 2 stacks a few transformer blocks before the final cross-attention).",
  },
  {
    id: 31,
    topic: "usage",
    q: "How does V-JEPA 2-AC choose robot actions?",
    opts: [
      "It imagines outcomes of sampled action sequences in latent space and picks those closest (L1) to the goal image's representation, replanning after each action.",
      "It imitates human demonstrations directly.",
      "It generates future video frames and picks the prettiest.",
      "It uses a reward function engineered for each task.",
    ],
    correct: 0,
    exp: "Model-predictive control in representation space: CEM samples actions, the predictor imagines, energy = L1 distance to the goal, execute the first action, repeat.",
  },
  {
    id: 32,
    topic: "usage",
    q: "For a dissertation on a free Colab T4, the sensible way to use V-JEPA 2 for action classification is:",
    opts: [
      "Pretrain V-JEPA 2 from scratch.",
      "Fine-tune the full ViT-g end to end.",
      "Freeze the encoder, cache its features, and train an attentive probe.",
      "Use only a linear probe on raw pixels.",
    ],
    correct: 2,
    exp: "Frozen features fit the compute budget, can be cached once, and give the standard, fair evaluation of the world model.",
  },
];

export const WORLD_MODELS_TOPIC_LABELS: Record<string, string> = {
  overview: "What a World Model Is",
  ingredients: "The Three Ingredients",
  pixel_latent: "Pixel vs Latent",
  collapse: "Collapse",
  family: "Family Tree",
  ijepa: "Anatomy of I-JEPA",
  vjepa: "From I-JEPA to V-JEPA",
  usage: "How to Use One",
};

export const WORLD_MODELS_SECTIONS: Section[] = [
  {
    id: "inicio",
    num: "00",
    title: "What a World Model Is",
    subtitle: "Learning by predicting, not by labeling",
  },
  {
    id: "ingredients",
    num: "01",
    title: "The Three Ingredients",
    subtitle: "Encoder, predictor, loss",
  },
  {
    id: "pixel_latent",
    num: "02",
    title: "Pixel vs Latent",
    subtitle: "Why predicting pixels blurs",
  },
  {
    id: "collapse",
    num: "03",
    title: "Collapse",
    subtitle: "The zero-loss cheat and its fixes",
  },
  {
    id: "family",
    num: "04",
    title: "Family Tree",
    subtitle: "From dreaming agents to V-JEPA 2",
  },
  {
    id: "ijepa",
    num: "05",
    title: "Anatomy of I-JEPA",
    subtitle: "Three networks, two masks, one loss",
  },
  {
    id: "vjepa",
    num: "06",
    title: "From I-JEPA to V-JEPA",
    subtitle: "Tubelets, tube masks, V-JEPA 2",
  },
  {
    id: "usage",
    num: "07",
    title: "How to Use One",
    subtitle: "Probes, fine-tuning, planning",
  },
  {
    id: "roadmap",
    num: "→",
    title: "Roadmap",
    subtitle: "Where this caderno is going",
  },
  {
    id: "simulado",
    num: "∞",
    title: "Final Simulation",
    subtitle: "32 exam-style questions",
  },
];
